import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from '@/redux/ReduxProvider'; // Import ReduxProvider
import { AuthProvider } from "@/services/AuthContext";
import { GroupMemberAuthProvider } from "@/services/GroupMemberAuthContext"; // Import GroupMemberAuthProvider

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <GroupMemberAuthProvider> {/* Wrap children with GroupMemberAuthProvider */}
              {children}
            </GroupMemberAuthProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}